# Generated by Django 5.1.4 on 2025-12-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="Webhook endpoint URL", max_length=500),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("product_created", "Product Created"),
                            ("product_updated", "Product Updated"),
                            ("product_deleted", "Product Deleted"),
                            ("product_imported", "Products Imported"),
                            ("bulk_delete", "Bulk Delete"),
                        ],
                        help_text="Event type that triggers this webhook",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the webhook is active"
                    ),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_response_code", models.IntegerField(blank=True, null=True)),
                ("last_response_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="webhooks_we_event_t_36de0b_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="webhooks_we_is_acti_683202_idx"
                    ),
                ],
            },
        ),
    ]
