# Generated by Django 5.1.4 on 2025-12-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Product price",
                max_digits=10,
                null=True,
            ),
        ),
    ]
