# Generated by Django 5.1.4 on 2025-12-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadjob",
            name="duplicate_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="skipped_rows",
            field=models.IntegerField(default=0),
        ),
    ]
